// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/zaccaron07/goexpert-weather-api-lab01/internal/entity"
	"github.com/zaccaron07/goexpert-weather-api-lab01/internal/infra/repo"
	"github.com/zaccaron07/goexpert-weather-api-lab01/internal/infra/web"
)

// Injectors from wire.go:

func NewWeatherHandler() *web.WebWeatherHandler {
	webWeatherHandler := web.NewWebWeatherHandler()
	return webWeatherHandler
}

// wire.go:

var setZipcodeRepository = wire.NewSet(repo.NewZipcodeRepository, wire.Bind(new(entity.ZipcodeRepositoryInterface), new(repo.ZipcodeRepository)))

var setWeatherRepository = wire.NewSet(repo.NewWeatherRepository, wire.Bind(new(entity.WeatherRepositoryInterface), new(repo.WeatherRepository)))
